issue-845-fix: True
resolve-type-alias: False
with-expecter: true
disable-version-string: True
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/services/settings/pkg/settings:
        config:
          dir: "pkg/settings/mocks"
        interfaces:
            Manager:
