issue-845-fix: True
resolve-type-alias: False
with-expecter: true
disable-version-string: True
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/services/collaboration/pkg/connector:
        config:
            dir: "mocks"
        interfaces:
            ConnectorService:
            ContentConnectorService:
            FileConnectorService:
    github.com/opencloud-eu/opencloud/services/collaboration/pkg/locks:
        config:
            dir: "mocks"
        interfaces:
            LockParser:
    github.com/opencloud-eu/reva/v2/pkg/rgrpc/todo/pool:
        config:
            dir: "mocks"
        interfaces:
            Selectable:
                config:
                    filename: "gateway_selector.go"
