issue-845-fix: True
resolve-type-alias: False
with-expecter: true
disable-version-string: True
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/pkg/keycloak:
        config:
            dir: "pkg/backends/keycloak/mocks"
        interfaces:
            Client:
