---

when:
  - event: ["push", "manual"]
    branch: main

steps:
  - name: devdocs
    image: codeberg.org/xfix/plugin-codeberg-pages-deploy:1
    settings:
      folder: docs
      branch: docs
      git_config_email: ${CI_COMMIT_AUTHOR_EMAIL}
      git_config_name: ${CI_COMMIT_AUTHOR}
      ssh_key:
        from_secret: ssh_key
